services:
   SequelizeDemo:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD : postgres
         POSTGRES_USER : postgres
         POSTGRES_DB : postgres
         POSTGRES_HOST : localhost
      ports:
         - 5432:5432   