services:
  redis:
    image: redis:alpine

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
